### ISSUE TITLE
wav_to_spectogram.py stops converting before it should

### ISSUE THREAD

**Issue by ibro45** [HPI-DeepLearning/crnn-lid#11]
Hi,

I'm working with four languages and for each I have downloaded only one video so that I can check that the scripts work as they should before running them on my VM on the cloud. 

The issue I have is that the script _wav_to_spectogram.py_ acts weird with one language.
The languages and the number of segmented .wav file for each are:

- Croatian - 64
- English - 42
- French - 39
- Spanish - 45

So, the expected result after running the script is that there will be 38 or 39 .png spectograms for each language since the language with the least number of .wav files is French. It does execute as it should when I run it for all the languages except English:

![w/o English](https://i.imgur.com/pa7puX9.png "w/o English")

But running the script with English manages to count only 13 files in English, even though there are 42:

![w/ English](https://i.imgur.com/zGLxWl7.png "w/ English")

I still haven't come up with an explanation to why it's happening, so any clue would be of a great help!

Here's the _sources.yml_ that I used to download the videos if someone prefers to check it himself. 
```
croatian:
  users:
    -
  playlists:
    - https://www.youtube.com/playlist?list=PLv3j2_RROTdEh39boAuP-JPeDR7dy6wih

english:
  users:
    - 
  playlists:
    - https://www.youtube.com/playlist?list=PLv3j2_RROTdHSp1oIY4L_t5xX0dFV3GMH

french:
  users:
    - 
  playlists:
    - https://www.youtube.com/playlist?list=PLv3j2_RROTdEgT-oLhk11Xjbev7Q02F3-
spanish:
  users:
    - 
  playlists:
    - https://www.youtube.com/playlist?list=PLv3j2_RROTdHpKmps4DaomrqXd8VmZV1g

```

I'd also note that I'm working with 3-seconds segments, so if someone will be recreating what I am doing, it is important to change the number of seconds by which the files will be splitted. It is on the line 66 in _download_youtube.py_ from:

`command = ["ffmpeg", "-y", "-i", f, "-map", "0", "-ac", "1", "-ar", "16000", "-f", "segment", "-segment_time", "10", output_filename]`

to: 

`command = ["ffmpeg", "-y", "-i", f, "-map", "0", "-ac", "1", "-ar", "16000", "-f", "segment", "-segment_time", "3", output_filename]`

For the same reason, it is necessary to change the size of the output spectogram on line 70 in _wav_to_spectogram.py_ from:

`parser.add_argument('--shape', dest='shape', default=[129, 500, 1], type=int, nargs=3)`

to: 

`parser.add_argument('--shape', dest='shape', default=[129, 150, 1], type=int, nargs=3)`

Thank you!
